apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator
          image: gaurav123shub/calculator-app:1.0
       imagePullSecrets:
       - name: regcred
         
          ports:
            - containerPort: 5000
